apiVersion: apps/v1
kind: Deployment
metadata:
  name: finzip-backend
  labels:
    app: finzip-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finzip-backend
  template:
    metadata:
      labels:
        app: finzip-backend
    spec:
      containers:
      - name: finzip-backend
        image: finzip-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: finzip-backend-service
spec:
  selector:
    app: finzip-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer 