name: Deploy Backend to EC2

on:
  push:
    branches:
      - dev  # Run only when changes are pushed to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the backend folder
            cd /home/ec2-user/app/backend  

            # Ensure Git and Node.js are installed
            sudo yum install -y git
            if ! command -v node &> /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Pull latest changes from GitHub
            git reset --hard
            git pull origin dev

            # Install dependencies
            npm install --production  # Install only production dependencies

            # Ensure PM2 is installed globally
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Restart backend using PM2 (or start if not running)
            pm2 restart finzip-backend || pm2 start src/index.js --name finzip-backend

            # Save PM2 process so it starts on reboot
            pm2 save
